server:
    port: 8080

spring:
    freemarker:
        prefix:
        suffix: .html

datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/background_template?characterEncoding=utf8
    username: root
    password: root
    maximumPoolSize: 10
